@startuml

actor User as User

User -> ShoppingCart : processOrder()
activate ShoppingCart
ShoppingCart -> Order : addProduct()
activate Order
Order -> Product : getStock()
activate Product
Product --> Order : getStock(): stock == 0
deactivate Product
Order --> ShoppingCart : addProduct: false
deactivate Order
ShoppingCart --> User : processOrder(): false
deactivate ShoppingCart

@enduml