@startuml

actor "Ragnhild die Große" as User

group loop [while adding products]
User -> Product : addToCart()
activate Product

Product -> ShoppingCart : addItem(Product)
deactivate Product
end

User -> ShoppingCart : processOrder()
activate ShoppingCart

ShoppingCart --> Order : create

group loop [for product in products]
ShoppingCart -> Order : addItem()
end

ShoppingCart -> Order : processOrder()
deactivate ShoppingCart

note right : Hier erstellt Order einen String,\nin dem alle Products mit amount\nund price gelistet werden und dann\nals .txt-Datei gespeichert wird.

@enduml