export const ROUTES = {
    HOME: '/',
    MANAGE_USERS: '/manage-users',
    LOGIN: '/login',
    LOGOUT: '/logout',
    SIGNUP: '/signup',
    CART: '/cart',
    CHECKOUT: '/checkout',
    PRODUCT_PAGE: '/products/:productId',
    ORDERS: '/orders',
    PROFILE: '/profile',
    NOTIFICATION: '/notification',
    MANAGE_PRODUCTS: '/manage-products',
    CONTACT: '/contact',
} as const;