-- Drop the not null constraint (you can use ALTER TABLE depending on your database)
--ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- Insert users into USERX table
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00', '+436601234', 'admin@duckmail.com');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Ragnhild', 'Die-Große', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00', '+436604321', 'ragnhild@die_große.at');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00', '+496600000', 'mustermannMaximilian@muster_mail.muster');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Ayleen', 'Edenhauser', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'Ayleen', NULL, '2024-01-01 00:00:00', '+496601234', 'Ayleen@Edenhauser.com');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Matteo', 'Volperino', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'Matteo', NULL, '2024-01-01 00:00:00', '+496601234', 'Matteo@Volperino.com');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Ljonja', 'Georg Mikhailovic Stommel ', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'Ljonja', NULL, '2024-01-01 00:00:00', '+496601234', 'Ljonja@Stommel.com');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE, PHONE, EMAIL)
VALUES (TRUE, 'Jakob', 'Oberhofer', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'Jakob', NULL, '2024-01-01 00:00:00', '+496601234', 'Jakob@Oberhofer.com');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ayleen'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ayleen'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Matteo'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Matteo'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ljonja'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ljonja'), 'CUSTOMER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Jakob'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Jakob'), 'CUSTOMER');

-- Insert preferred notification channels into USERX_PREFERRED_CHANNELS table by looking up the corresponding user ID
INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'EMAIL');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'WHATSAPP');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'SMS');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'WHATSAPP');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'SMS');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'SMS');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ayleen'), 'WHATSAPP');

INSERT INTO USERX_PREFERRED_CHANNELS(USERX_ID, PREFERRED_CHANNELS)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'Ayleen'), 'EMAIL');

-- Update CREATE_USER_ID fields after the initial insert
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'admin';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user1';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user2';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'Ayleen') WHERE USERNAME = 'Ayleen';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'Matteo') WHERE USERNAME = 'Matteo';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'Ljonja') WHERE USERNAME = 'Ljonja';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'Jakob') WHERE USERNAME = 'Jakob';

-- Add the not null constraint back
--ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;
--it is necessary for CREATE_USER_ID to be null, for users who get created via the Sign-Up page
