package at.qe.skeleton.model;

import jakarta.persistence.*;

import java.io.Serializable;
import java.util.Objects;
import java.util.Set;


/**
 * Entity representing a product in the shop.
 * <p>
 * This class stores core product details such as name, price, stock, and discount levels.
 * It is associated with multiple {@link ProductCategory} enums to allow filtering and categorization.
 */
@Entity
public class Product implements Serializable {

    /**
     * Serial version UID for serialization consistency.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier for the product, automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The display name of the product.
     */
    @Column(nullable = false)
    private String name;

    /**
     * A detailed description of the product features.
     */
    private String description;

    /**
     * The base price of the product without discounts.
     */
    @Column(nullable = false)
    private double price;

    /**
     * The current quantity available in the warehouse.
     */
    @Column(nullable = false)
    private long stock;

    /**
     * The discount applied to the product (e.g., 0.2 for 20% off).
     */
    private double discount;

    /**
     * URL or path to the product image.
     */
    private String imageUrl;

    /**
     * A set of categories associated with this product for filtering purposes.
     * Persisted in a separate collection table {@code product_category}.
     */
    @ElementCollection(targetClass = ProductCategory.class, fetch = FetchType.LAZY)
    @CollectionTable(name = "product_category", joinColumns = @JoinColumn(name = "product_id"))
    @Enumerated(EnumType.STRING)
    private Set<ProductCategory> categories;


    // ===== Getter/Setter/Equals/HashCode =====

    /**
     * @return the unique ID of the product
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the unique ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the product name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the product name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the product description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the base price of the product
     */
    public double getPrice() {
        return price;
    }

    /**
     * @param price the price to set
     */
    public void setPrice(double price) {
        this.price = price;
    }

    /**
     * @return the current stock level
     */
    public long getStock() {
        return stock;
    }

    /**
     * @param stock the stock level to set
     */
    public void setStock(long stock) {
        this.stock = stock;
    }

    /**
     * @return the current discount level (0.0 to 1.0)
     */
    public double getDiscount() {
        return discount;
    }

    /**
     * @param discount the discount level to set
     */
    public void setDiscount(double discount) {
        this.discount = discount;
    }

    /**
     * @return the image source path
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * @param imageUrl the image source path to set
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * @return the set of categories this product belongs to
     */
    public Set<ProductCategory> getCategories() {
        return categories;
    }

    /**
     * @param categories the set of categories to set
     */
    public void setCategories(Set<ProductCategory> categories) {
        this.categories = categories;
    }

    /**
     * Compares this product with another object based on the unique ID.
     *
     * @param o the object to compare with
     * @return {@code true} if IDs match, {@code false} otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(id, product.id);
    }

    /**
     * Generates a hash code based on the product ID.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}